-- 2024 AMC 10B Problems/Problem 15
-- Source: AoPS Wiki
-- URL: https://artofproblemsolving.com/wiki/index.php?title=2024_AMC_12B_Problems/Problem_10

-- Problem (LaTeX):
/-
A list of $9$ real numbers consists of $1$ , $2.2$ , $3.2$ , $5.2$ , $6.2$ , and $7$ , as well as $x$ , $y$ , and $z$ with $x$ $\le$ $y$ $\le$ $z$ . The range of the list is $7$ , and the mean and the median are both positive integers. How many ordered triples ( $x$ , $y$ , $z$ ) are possible? $\textbf{(A) } 1 \qquad \textbf{(B) } 2 \qquad \textbf{(C) } 3 \qquad \textbf{(D) } 4 \qquad \textbf{(E) } \text{infinitely many}$
-/

-- Solution/Answer (LaTeX):
/-
$\textbf{First Case}$ We start off by knowing that there must exist an ordered pair \( (0,y,z) \) and a big term 7 such that the range is satisfied and the median could also be satisfied. Because \( x \le y \le z \), we say \( x=0 \). Then, we get the sum 24.8. We need \( \frac{24.8 +y +z}{9} \in \mathbb{Z} \). This means that we need the nearest multiple of 9, which is 36, and we get \( y+z = 11.2 \). We need one of these to be the median, WLOG say \( y \). Then, \( y \in \{4,5\} \). So if \( y=4 \), we get \( z=7.2 \), and if \( y=5 \), we get 6.2. We see that if \( z=6.2 \), the range will still remain as 7, and therefore the one ordered triple \( (0,5,6.2) \) satisfies this. We know that the median can be \( y \), so we have \( y \in \{4,5\} \). We do casework on 4 and 5. $\textbf{Case 1}$ Say \( y=4 \). Then, because we already know there exists an ordered triple where \( z \) is not the largest, there must exist at least one ordered triple where \( z \) is, so we say \( z-x=7 \). We also know that the mean must be divisible by 9. Quickly summing each number up we get 24.8. The next number divisible by 9 is 36. We add \( y \) to get 28.8. We then know \( x+z=36-28.8=7.2 \). The smallest values give \( x=0.1 \) and \( z=7.1 \). This satisfies our constraints. We don't want any errors, so we check the next sum, which is 45. We get then \( 7.2=x+z \) and \( z-x=7 \). This gives \( x=4.6 \) and \( z=11.6 \). This is a contradiction, as \( x \le y \le z \), and the values incrementally become too large, and therefore we only have one ordered triple for this case, which is \( (0.1,4,7.1) \) $\textbf{Case 2}$ We now check \( y=5 \). This makes our sum 29.8. The nearest multiple of 9 is 36, again. This gives us \( 6.2 = x+z \) and \( z-x=7 \). Solving gives us -0.4 and 6.6. This however doesn't work, as 6.6 is not the greatest value. We decide to check the next multiple of 9, which is 45. This gives us \( 15.2 = x+z \) and \( z-x=7 \). This gives us \( x=4.1 \) and \( z=11.1 \). This also doesn't work, as \( x \) becomes incrementally larger, and therefore there are no ordered triples that satisfy this. $\textbf{Last Case}$ We have one more case, and that is \(x\) is not the first number, but \( z \) is the last, meaning \( z-1=7 \), and \( z=8 \). This means that \( \frac{24.8+x+y+z}{9} \in \mathbb{Z} \). So, if \( z=8 \), we get 32.8. We again see that we need the nearest multiple of 9 which is 36, and we get \( 3.2 = x+y \). We see that \( x \) and \( y \) still need to be a integer median and 3.2 is too small, so 36 cannot work. We try 45, and see \( 12.2 = x+y \). After some trial and error, we see that \( x=6 \) and \( y=6.2 \), giving us the ordered triple \( (6,6.2,8) \). Continuing as before shows us that \( x \) again incrementally increases, and therefore we have only one ordered triple. We have $\boxed{\textbf{(C) }3}$ ordered triples. These are \( (0.1,4,7.1) \), \( (0,5,6.2) \), and \( (6,6.2,8) \). ~Pinotation
-/

import Mathlib.Tactic

theorem wiki_index_php_30ff0f0377 : Prop := by
  sorry
